export const carsData = [
  {
    id: 1,
    title: "Koenigsegg",
    class: "Sport",
    gas: "90L",
    gearbox: "Manual",
    people: "2 People",
    price: "99.00",
    imageUrl: "/assets/images/car1.png",
    heart: "/assets/images/heart.svg",
  },
  {
    id: 2,
    title: "Nissan GT - R",
    class: "Sport",
    gas: "80L",
    gearbox: "Manual",
    people: "2 People",
    price: "80.00",
    imageUrl: "/assets/images/car2.png",
    heart: "/assets/images/heart.svg",
  },
  {
    id: 3,
    title: "Rolls - Royce",
    class: "Sedan",
    gas: "70L",
    gearbox: "Manual",
    people: "4 People",
    price: "96.00",
    imageUrl: "/assets/images/car3.png",
    heart: "/assets/images/heart.svg",
  },
  {
    id: 4,
    title: "All New Rush",
    class: "SUV",
    gas: "70L",
    gearbox: "Manual",
    people: "6 People",
    price: "72.00",
    imageUrl: "/assets/images/car4.png",
    heart: "/assets/images/heart.svg",
  },
  {
    id: 5,
    title: "CR  - V",
    class: "SUV",
    gas: "80L",
    gearbox: "Manual",
    people: "6 People",
    price: "80.00",
    imageUrl: "/assets/images/car5.png",
    heart: "/assets/images/heart.svg",
  },
  {
    id: 6,
    title: "All New Terios",
    class: "SUV",
    gas: "90L",
    gearbox: "Manual",
    people: "6 People",
    price: "74.00",
    imageUrl: "/assets/images/car6.png",
    heart: "/assets/images/heart.svg",
  },
  {
    id: 7,
    title: "MG ZX Exclusice",
    class: "Hatchback",
    gas: "70L",
    gearbox: "Manual",
    people: "4 People",
    price: "76.00",
    imageUrl: "/assets/images/car7.png",
    heart: "/assets/images/heart.svg",
  },
  {
    id: 8,
    title: "New MG ZS",
    class: "SUV",
    gas: "80L",
    gearbox: "Manual",
    people: "6 People",
    price: "80.00",
    imageUrl: "/assets/images/car8.png",
    heart: "/assets/images/heart.svg",
  },
  {
    id: 9,
    title: "MG ZX Excite",
    class: "Hatchback",
    gas: "90L",
    gearbox: "Manual",
    people: "4 People",
    price: "74.00",
    imageUrl: "/assets/images/car9.png",
    heart: "/assets/images/heart.svg",
  },
];
